prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorNamespaceSelector: {}

grafana:
  defaultDashboardsTimezone: browser
  sidecar:
    datasources:
      defaultDatasourceEnabled: true
      isDefaultDatasource: true
      name: Prometheus
      uid: prometheus
      url: http://kube-prometheus-stack-prometheus.monitoring.svc:9090
