apiVersion: apps/v1
kind: Deployment
metadata:
  name: fsa-be
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fsa-be
  template:
    metadata:
      labels:
        app: fsa-be
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: fsa-be
          image: acrfsamatolaka.azurecr.io/fsa-backend:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: keycloak
            - name: DB_URL
              value: jdbc:postgresql://psql-fsa-matolaka.postgres.database.azure.com:5432/fsa-db
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: db_password
            - name: KEYCLOAK_JWK_SET_URI
              value: https://20-234-19-239.sslip.io/auth/realms/skill-market/protocol/openid-connect/certs
            - name: KEYCLOAK_BASE_URL
              value: https://20-234-19-239.sslip.io/auth
            - name: KEYCLOAK_REALM
              value: skill-market
            - name: KEYCLOAK_CLIENT_ID
              value: skill-market-client
            - name: KEYCLOAK_ADMIN_REALM
              value: master
            - name: KEYCLOAK_ADMIN_CLIENT_ID
              value: admin-cli
            - name: KEYCLOAK_ADMIN_USERNAME
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-secret
                  key: kc_password
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
          ports:
            - name: http
              containerPort: 8080
